package com.example.model

enum class AppLanguage(val code: String, val displayName: String) {
    HINDI("HI", "हिन्दी (Hindi)"),
    ENGLISH("EN", "English")
}

object Strings {
    fun get(key: String, lang: AppLanguage): String {
        val map = if (lang == AppLanguage.HINDI) hindiStrings else englishStrings
        return map[key] ?: englishStrings[key] ?: key
    }

    private val hindiStrings = mapOf(
        "app_name" to "माई स्टडी प्लानर",
        "app_subtitle" to "योजना • अध्ययन • ट्रैक • सुधार",
        "nav_dashboard" to "डैशबोर्ड",
        "nav_tasks" to "कार्य सूची",
        "nav_quiz_hub" to "क्विज़ व GK",
        "nav_timeline" to "समय-सारणी",
        "nav_timer" to "टाइमर",
        "nav_calendar" to "कैलेंडर",
        "nav_analytics" to "एनालिटिक्स",
        "nav_settings" to "सेटिंग्स",
        "greeting_morning" to "शुभ प्रभात",
        "greeting_afternoon" to "शुभ दोपहर",
        "greeting_evening" to "शुभ संध्या",
        "today_target" to "आज का लक्ष्य",
        "hours_study" to "घंटे अध्ययन",
        "planned_tasks" to "नियोजित कार्य",
        "completed_tasks" to "पूर्ण कार्य",
        "pending_tasks" to "लंबित कार्य",
        "overdue_tasks" to "अतिदेय / छूटे कार्य",
        "completion_rate" to "पूर्णता प्रतिशत",
        "study_time" to "अध्ययन समय",
        "work_time" to "कार्य समय",
        "productivity_status" to "उत्पादकता स्थिति",
        "today_remark" to "आज की टिप्पणी",
        "status_excellent" to "उत्कृष्ट 🌟",
        "status_very_good" to "बहुत बढ़िया 🚀",
        "status_good" to "अच्छा 👍",
        "status_improving" to "सुधार जारी 📈",
        "status_start_fresh" to "शुरुआत करें 🌱",
        "quick_actions" to "त्वरित क्रियाएं",
        "action_add_task" to "नया कार्य",
        "action_start_study" to "पढ़ाई शुरू",
        "action_focus_timer" to "फ़ोकस टाइमर",
        "action_calendar" to "कैलेंडर",
        "action_analytics" to "रिपोर्ट देखें",
        "action_today_tasks" to "आज के कार्य",
        "action_daily_report" to "दिन की रिपोर्ट",
        "action_weekly_report" to "साप्ताहिक रिपोर्ट",
        "search_hint" to "कार्य या विषय खोजें...",
        "filter_all" to "सभी",
        "filter_today" to "आज",
        "filter_pending" to "लंबित",
        "filter_completed" to "पूर्ण",
        "filter_overdue" to "छूटे हुए",
        "add_task_title" to "नया कार्य जोड़ें",
        "edit_task_title" to "कार्य संपादित करें",
        "task_name" to "कार्य का नाम",
        "task_name_hint" to "उदा. NCERT इतिहास अध्याय 4",
        "subject" to "विषय / श्रेणी",
        "description" to "विवरण (वैकल्पिक)",
        "priority" to "प्राथमिकता",
        "task_type" to "कार्य का प्रकार",
        "start_date" to "प्रारंभ तिथि",
        "start_time" to "प्रारंभ समय",
        "end_date" to "समाप्ति तिथि",
        "end_time" to "समाप्ति समय",
        "duration" to "अनुमानित अवधि (मिनट)",
        "reminder" to "अनुस्मारक (रिमाइंडर)",
        "save_task" to "कार्य सहेजें",
        "cancel" to "रद्द करें",
        "delete" to "हटाएं",
        "reschedule" to "पुनर्निर्धारित करें",
        "reschedule_title" to "कार्य को आगे बढ़ाएं",
        "reschedule_tomorrow" to "कल के लिए",
        "reschedule_custom" to "अन्य तिथि चुनें",
        "study_streak" to "अध्ययन स्ट्रीक",
        "days_streak" to "दिनों की स्ट्रीक",
        "keep_streak_alive" to "अपनी निरंतरता बनाए रखें!",
        "timer_pomodoro" to "पोमोडोरो (25m)",
        "timer_study" to "अध्ययन (50m)",
        "timer_deep" to "गहन अध्ययन (90m)",
        "timer_custom" to "कस्टम टाइमर",
        "timer_select_subject" to "विषय चुनें",
        "timer_start" to "शुरू करें",
        "timer_pause" to "रोकें",
        "timer_resume" to "जारी रखें",
        "timer_stop" to "समाप्त करें",
        "timer_reset" to "रीसेट",
        "timer_recent_sessions" to "हाल के अध्ययन सत्र",
        "daily_report_title" to "आज की अध्ययन रिपोर्ट",
        "weekly_report_title" to "साप्ताहिक प्रदर्शन रिपोर्ट",
        "most_studied_subject" to "सर्वाधिक पढ़ा गया विषय",
        "settings_title" to "सेटिंग्स और लक्ष्य",
        "language_option" to "भाषा (Language)",
        "theme_option" to "थीम मोड",
        "daily_target_hours" to "दैनिक अध्ययन लक्ष्य (घंटे)",
        "daily_target_tasks" to "दैनिक कार्य लक्ष्य (संख्या)",
        "weekly_target_hours" to "साप्ताहिक अध्ययन लक्ष्य (घंटे)",
        "custom_remarks_title" to "प्रदर्शन टिप्पणियां अनुकूलित करें",
        "save_settings" to "सेटिंग्स सहेजें",
        "notification_permission_tip" to "समय पर अनुस्मारक पाने के लिए नोटिफिकेशन चालू करें",
        "enable_notifications" to "नोटिफिकेशन चालू करें",
        "no_tasks_today" to "आज के लिए कोई कार्य निर्धारित नहीं है। नया कार्य जोड़ें!",
        "all_tasks_completed" to "शाबाश! आज के सभी कार्य पूर्ण हो चुके हैं 🎉",
        "priority_low" to "कम",
        "priority_medium" to "मध्यम",
        "priority_high" to "उच्च",
        "priority_urgent" to "अति आवश्यक",
        "type_study" to "अध्ययन",
        "type_revision" to "पुनरावृत्ति",
        "type_homework" to "गृहकार्य",
        "type_assignment" to "असाइनमेंट",
        "type_exam_prep" to "परीक्षा तैयारी",
        "type_reading" to "पठन",
        "type_exercise" to "व्यायाम",
        "type_personal" to "व्यक्तिगत कार्य",
        "type_other" to "अन्य",
        "rem_none" to "कोई अनुस्मारक नहीं",
        "rem_5m" to "5 मिनट पहले",
        "rem_10m" to "10 मिनट पहले",
        "rem_15m" to "15 मिनट पहले",
        "rem_30m" to "30 मिनट पहले",
        "rem_1h" to "1 घंटा पहले",
        "mark_complete" to "पूर्ण चिह्नित करें",
        "mark_pending" to "लंबित चिह्नित करें"
    )

    private val englishStrings = mapOf(
        "app_name" to "My Study Planner",
        "app_subtitle" to "Plan • Study • Track • Improve",
        "nav_dashboard" to "Dashboard",
        "nav_tasks" to "Tasks",
        "nav_quiz_hub" to "Quiz & GK",
        "nav_timeline" to "Timeline",
        "nav_timer" to "Focus Timer",
        "nav_calendar" to "Calendar",
        "nav_analytics" to "Analytics",
        "nav_settings" to "Settings",
        "greeting_morning" to "Good Morning",
        "greeting_afternoon" to "Good Afternoon",
        "greeting_evening" to "Good Evening",
        "today_target" to "Today's Target",
        "hours_study" to "Hours Study",
        "planned_tasks" to "Planned Tasks",
        "completed_tasks" to "Completed",
        "pending_tasks" to "Pending",
        "overdue_tasks" to "Overdue",
        "completion_rate" to "Completion Rate",
        "study_time" to "Study Time",
        "work_time" to "Work Time",
        "productivity_status" to "Productivity Status",
        "today_remark" to "Today's Remark",
        "status_excellent" to "Excellent 🌟",
        "status_very_good" to "Very Good 🚀",
        "status_good" to "Good 👍",
        "status_improving" to "Improving 📈",
        "status_start_fresh" to "Let's Begin 🌱",
        "quick_actions" to "Quick Actions",
        "action_add_task" to "Add Task",
        "action_start_study" to "Start Study",
        "action_focus_timer" to "Focus Timer",
        "action_calendar" to "Calendar",
        "action_analytics" to "Analytics",
        "action_today_tasks" to "Today's Tasks",
        "action_daily_report" to "Daily Report",
        "action_weekly_report" to "Weekly Report",
        "search_hint" to "Search task or subject...",
        "filter_all" to "All",
        "filter_today" to "Today",
        "filter_pending" to "Pending",
        "filter_completed" to "Completed",
        "filter_overdue" to "Overdue",
        "add_task_title" to "Add New Task",
        "edit_task_title" to "Edit Task",
        "task_name" to "Task Name",
        "task_name_hint" to "e.g. History NCERT Chapter 4",
        "subject" to "Subject / Category",
        "description" to "Description (Optional)",
        "priority" to "Priority",
        "task_type" to "Task Type",
        "start_date" to "Start Date",
        "start_time" to "Start Time",
        "end_date" to "End Date",
        "end_time" to "End Time",
        "duration" to "Estimated Duration (mins)",
        "reminder" to "Reminder",
        "save_task" to "Save Task",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "reschedule" to "Reschedule",
        "reschedule_title" to "Reschedule Task",
        "reschedule_tomorrow" to "Move to Tomorrow",
        "reschedule_custom" to "Pick Another Date",
        "study_streak" to "Study Streak",
        "days_streak" to "Day Streak",
        "keep_streak_alive" to "Keep your streak alive!",
        "timer_pomodoro" to "Pomodoro (25m)",
        "timer_study" to "Study (50m)",
        "timer_deep" to "Deep Study (90m)",
        "timer_custom" to "Custom Timer",
        "timer_select_subject" to "Select Subject",
        "timer_start" to "Start",
        "timer_pause" to "Pause",
        "timer_resume" to "Resume",
        "timer_stop" to "Stop",
        "timer_reset" to "Reset",
        "timer_recent_sessions" to "Recent Study Sessions",
        "daily_report_title" to "Today's Study Report",
        "weekly_report_title" to "Weekly Performance Report",
        "most_studied_subject" to "Most Studied Subject",
        "settings_title" to "Settings & Targets",
        "language_option" to "Language",
        "theme_option" to "Theme Mode",
        "daily_target_hours" to "Daily Study Target (Hours)",
        "daily_target_tasks" to "Daily Task Target (Count)",
        "weekly_target_hours" to "Weekly Study Target (Hours)",
        "custom_remarks_title" to "Customize Performance Remarks",
        "save_settings" to "Save Settings",
        "notification_permission_tip" to "Enable notifications to receive timely study reminders",
        "enable_notifications" to "Enable Notifications",
        "no_tasks_today" to "No tasks planned for today. Tap + to add one!",
        "all_tasks_completed" to "Great job! All planned tasks completed today 🎉",
        "priority_low" to "Low",
        "priority_medium" to "Medium",
        "priority_high" to "High",
        "priority_urgent" to "Urgent",
        "type_study" to "Study",
        "type_revision" to "Revision",
        "type_homework" to "Homework",
        "type_assignment" to "Assignment",
        "type_exam_prep" to "Exam Preparation",
        "type_reading" to "Reading",
        "type_exercise" to "Exercise",
        "type_personal" to "Personal Work",
        "type_other" to "Other",
        "rem_none" to "No Reminder",
        "rem_5m" to "5 minutes before",
        "rem_10m" to "10 minutes before",
        "rem_15m" to "15 minutes before",
        "rem_30m" to "30 minutes before",
        "rem_1h" to "1 hour before",
        "mark_complete" to "Mark Complete",
        "mark_pending" to "Mark Pending"
    )
}
